### ISSUE TITLE
Request: Elementor Pro Form

### ISSUE THREAD

**Issue by pBrambi** [mosparo/wordpress-plugin#4]
Hello, 

it would be very nice, to have the plugin integrate into **Elementor Pro Forms.**

I am not experienced enough to so it myself, that why the request.

As a reference, maybe this could help: https://github.com/hCaptcha/hcaptcha-wordpress-plugin/tree/master/src/php/ElementorPro

**Thanks for the lovely work!**

**Comment by zepich** [comment]
As suggested by @pBrambi, we've investigated the Elementor Pro Form Builder and added a module to the mosparo Integration plugin to use mosparo in the Elementor Form Builder.

We've just released v1.4 of the mosparo Integration plugin, which contains the Elementor Form module.

@pBrambi Thank you for your suggestion and help to test the new module.
